# Disable automatic Kafka container
quarkus.kafka.devservices.enabled=true

# Disable automatic Database container
#quarkus.datasource.devservices.enabled=false

quarkus.http.port=8800
quarkus.http.ssl-port=8444

# mvn clean package -Dquarkus.kubernetes.deploy=true

quarkus.openshift.build-strategy=docker
quarkus.openshift.route.expose=true


kafka.bootstrap.servers=orl-clust-kafka-listener1-bootstrap-kafka-streams.apps.cluster-492gk.492gk.sandbox2076.opentlc.com:443
kafka.topic=nbp-data
kafka.security.protocol=SSL
kafka.ssl.truststore.location=/home/wrenk/CLIENTS/ORLEN/quarkus-ii/getting-started/truststore.jks
kafka.ssl.truststore.password=123456


