apiVersion: v1
kind: ConfigMap
metadata:
  name: quarkus-maven-settings
data:
  settings.xml: |
    <settings xmlns="http://maven.apache.org/SETTINGS/1.2.0" 
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
              xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.2.0 https://maven.apache.org/xsd/settings-1.2.0.xsd">
      <profiles>
        <profile>
          <id>red-hat-enterprise-maven-repository</id>
          <repositories>
            <repository>
              <id>red-hat-enterprise-maven-repository</id>
              <url>https://maven.repository.redhat.com/ga/</url>
              <releases>
                <enabled>true</enabled>
              </releases>
              <snapshots>
                <enabled>false</enabled>
              </snapshots>
            </repository>
          </repositories>
          <pluginRepositories>
            <pluginRepository>
              <id>red-hat-enterprise-maven-repository</id>
              <url>https://maven.repository.redhat.com/ga/</url>
              <releases>
                <enabled>true</enabled>
              </releases>
              <snapshots>
                <enabled>false</enabled>
              </snapshots>
            </pluginRepository>
          </pluginRepositories>
          <properties>
            <quarkus.platform.group-id>com.redhat.quarkus.platform</quarkus.platform.group-id>
            <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
            <quarkus.platform.version>3.27.2.redhat-00002</quarkus.platform.version>
          </properties>
        </profile>
      </profiles>
      <activeProfiles>
        <activeProfile>red-hat-enterprise-maven-repository</activeProfile>
      </activeProfiles>
    </settings>