apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: quarkus-run-
spec:
  params:
    - name: git-repository-url
      value: 'https://github.com/wrenkredhat2/O-X-Repo.git'
    - name: sslVerify
      value: 'false'
    - name: context-dir
      value: camel-quarkus
  pipelineRef:
    name: quarkus-build-pipeline-ui-impr-ii
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: source
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: gp3-csi
          volumeMode: Filesystem