apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - ../../../../argo-cd/keycloak

patches:

  - target:
      kind: Application
      name: keycloak
    patch: |
      - op: replace
        path: /spec/source/repoURL
        value: "https://github.com/wrenkredhat2/O-X-Repo.git"
      - op: replace
        path: /spec/source/path
        value: "RH-DEMO/overlays/rh-cluster/keycloak"
      - op: replace
        path: /spec/destination/server
        value: "https://kubernetes.default.svc"
