apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Ressourcen, die verwaltet werden sollen
resources:
  - argo-keycloak.yaml

# 2. Gemeinsame Metadaten für alle Ressourcen
namespace: openshift-gitops