apiVersion: v1
kind: Secret
metadata:
  name: git-token-secret
  annotations:
    tekton.dev/git-0: https://devops-sir.orlen.pl # Your internal Git URL
type: kubernetes.io/basic-auth
stringData:
  username: "anything" # For tokens, the username can often be anything or your email
  password: "YOUR_PERSONAL_ACCESS_TOKEN"