apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: qrks-build-trigger-template
  labels:
    app: quarkus-hello
spec:
  params:
    - name: git-repository-url
      default: "https://github.com/wrenkredhat2/O-X-Repo.git"
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: qrks-pl-
      spec:
        pipelineRef:
          name: quarkus-hello-build-pipeline
        params:
          - name: git-repository-url
            value: $(tt.params.git-repository-url)
        workspaces:
          - name: workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 100Mi