# Note the port is 443, NOT 9092 or 9094!
kafka.bootstrap.servers=olen-clust-kafka-external-bootstrap-myproject.apps.cluster.example.com:443
kafka.security.protocol=SSL
# You will also need to point to the truststore we talked about earlier
#kafka.ssl.truststore.location=/deployments/config/truststore.jks
kafka.ssl.truststore.password=123456
kafka.ssl.truststore.location=/home/wrenk/CLIENTS/ORLEN/quarkus-ii/getting-started/truststore.jks