# Note the port is 443, NOT 9092 or 9094!
kafka.bootstrap.servers=my-cluster-kafka-external-bootstrap-myproject.apps.cluster.example.com:443
kafka.security.protocol=SSL
# You will also need to point to the truststore we talked about earlier
#kafka.ssl.truststore.location=/deployments/config/truststore.jks
kafka.ssl.truststore.password=123456