apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: orl-clust
  namespace: kafka-streams
spec:
  kafka:
    # ...
    listeners:
      # ...
      - name: listener1
        port: 9094
        type: route
        tls: true
        configuration:
          bootstrap:
            host: orl-clust-kafka-listener1-bootstrap-kafka-streams.apps.dev.orlen.pl
      # --- NEW IINTERNAL LISTENER ---
      - name: internal
        port: 9092
        type: internal
        tls: false
  entityOperator:
    topicOperator: {}
    userOperator: {}