apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: orl-clust
  namespace: kafka-streams
spec:
  kafka:
    # ...
    listeners:
      # ...
      - name: listener1
        port: 9094
        type: route
        tls: true
  entityOperator:
    topicOperator: {}
    userOperator: {}