apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: orlen-cluster-pool
  namespace: kafka-streams
  labels:
    strimzi.io/cluster: orlen-cluster # Must match the name of your Kafka CR
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 20Gi
        deleteClaim: false