apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka-streams

resources:
  - rolebinding.yaml
  - ../../../kafka-streams/base

#namePrefix: prod-
#commonLabels:
#  env: production

# Mehr Power für Prod
#patches:

#  - target:
#      kind: APIManager
#      name: orlen-apimanager
#    patch: |-
#      - op: delete
#        path: /spec/kafka/listeners/
#       value: apps.cluster-492gk.492gk.sandbox2076.opentlc.com

