# --- Service ---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  labels:
    app: valkey
  annotations:
    argocd.argoproj.io/sync-wave: "00"
spec:
  selector:
    app: valkey
  ports:
    - name: tcp-6379
      port: 6379
      targetPort: 6379